const QUESTIONS_PIGEONHOLE = [
{"id": 3001, "year": 2024, "difficulty": "easy", "text": "There are 13 students and 12 months in a year. Each student picks their birth month. What is the minimum number of students guaranteed to share a birth month?", "choices": ["A) 1", "B) 2", "C) 3", "D) 4", "E) 5"], "answer": 1, "solution": "12 months = 12 pigeonholes, 13 students = 13 pigeons. By the Pigeonhole Principle, ⌈13/12⌉ = 2. At least 2 students must share a birth month."},
{"id": 3002, "year": 2024, "difficulty": "easy", "text": "A drawer has red, blue, and green socks mixed together. What is the minimum number of socks you must pull out (without looking) to guarantee a matching pair?", "choices": ["A) 2", "B) 3", "C) 4", "D) 5", "E) 6"], "answer": 2, "solution": "3 colours = 3 pigeonholes. Worst case: pick 1 red, 1 blue, 1 green (3 socks, all different). The 4th sock must match one already chosen. Answer: 4."},
{"id": 3003, "year": 2024, "difficulty": "easy", "text": "A class of 30 students has only 5 different surnames. What is the minimum number of students guaranteed to share the same surname?", "choices": ["A) 4", "B) 5", "C) 6", "D) 7", "E) 8"], "answer": 2, "solution": "⌈30/5⌉ = 6. By the Pigeonhole Principle, at least one surname must be shared by 6 or more students."},
{"id": 3004, "year": 2024, "difficulty": "medium", "text": "In a group of 367 people, what is guaranteed about their birthdays?", "choices": ["A) Two people share a birthday", "B) Three people share a birthday", "C) All birthdays are different", "D) Someone was born on Feb 29", "E) Nothing is guaranteed"], "answer": 0, "solution": "There are 366 possible birthdays (including Feb 29). With 367 people, by the Pigeonhole Principle at least 2 must share a birthday."},
{"id": 3005, "year": 2024, "difficulty": "medium", "text": "A bag has 10 red, 10 blue, and 10 green marbles. What is the minimum number you must draw (without looking) to guarantee 5 marbles of the same colour?", "choices": ["A) 5", "B) 10", "C) 13", "D) 15", "E) 18"], "answer": 2, "solution": "Worst case: draw 4 red + 4 blue + 4 green = 12 marbles with no colour reaching 5. The 13th draw guarantees 5 of one colour."},
{"id": 3006, "year": 2024, "difficulty": "medium", "text": "There are 5 pigeonholes and 11 pigeons. What is the minimum number of pigeons that must be in at least one hole?", "choices": ["A) 2", "B) 3", "C) 4", "D) 5", "E) 6"], "answer": 1, "solution": "⌈11/5⌉ = ⌈2.2⌉ = 3. At least one pigeonhole must contain 3 or more pigeons."},
{"id": 3007, "year": 2024, "difficulty": "medium", "text": "Among any 5 integers, at least two must have the same remainder when divided by 4. Why?", "choices": ["A) Because 5 > 4", "B) There are only 4 possible remainders (0,1,2,3), and 5 integers must reuse one", "C) Integers always repeat", "D) Division always gives the same result", "E) By coincidence"], "answer": 1, "solution": "Dividing by 4 gives remainders 0, 1, 2, or 3 — exactly 4 options. With 5 integers and only 4 possible remainders, by the Pigeonhole Principle at least two must share the same remainder."},
{"id": 3008, "year": 2024, "difficulty": "medium", "text": "A teacher has 25 students and assigns each a number from 1 to 8. At least how many students are guaranteed to have the same number?", "choices": ["A) 2", "B) 3", "C) 4", "D) 5", "E) 6"], "answer": 1, "solution": "⌈25/8⌉ = ⌈3.125⌉ = 4. At least 4 students must share the same number."},
{"id": 3009, "year": 2024, "difficulty": "hard", "text": "Among any 10 integers chosen from {1, 2, ..., 18}, prove two must sum to 19. How many pairs (a, b) with a + b = 19 exist within {1, ..., 18}?", "choices": ["A) 7", "B) 8", "C) 9", "D) 10", "E) 11"], "answer": 2, "solution": "The pairs summing to 19 are: (1,18),(2,17),(3,16),(4,15),(5,14),(6,13),(7,12),(8,11),(9,10) — exactly 9 pairs. With 10 numbers chosen, by the Pigeonhole Principle two must come from the same pair and therefore sum to 19."},
{"id": 3010, "year": 2024, "difficulty": "hard", "text": "A box contains socks in 7 different colours. What is the minimum number of socks you must draw to guarantee at least 3 socks of the same colour?", "choices": ["A) 7", "B) 10", "C) 14", "D) 15", "E) 21"], "answer": 3, "solution": "Worst case: draw 2 of each colour = 7×2 = 14 socks with no colour reaching 3. The 15th sock must give a third of some colour. Answer: 15."},
];